# .travis.yml
language: node_js
node_js:
  - '10'
cache:
  npm: true
install:
  - npm i
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - npm t && npm run build
deploy:
  provider: script
  script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage && GIT_USER="${GH_NAME}" npm run deploy
  skip_cleanup: true
  on:
    branch: master
